version: "3.7"
services:
    rabbit-mq1:
        image: rabbitmq:3.8.3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

    rabbit-mq2:
        image: rabbitmq:3.8.3-management
        ports:
            - "5673:5672"
            - "15673:15672"
        volumes:
            - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
